language: go
go:
    - tip
env:
    - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
    - go get github.com/mitchellh/gox
    - go get github.com/tcnksm/ghr
script:
    - go test -v ./...
    - cd cmd/chatty
    - go build
after_success:
    - gox -osarch="linux/amd64" -output "dist/{{.OS}}_{{.Arch}}"
    - ghr --username upframe --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/